import React, { useState } from 'react';
import { X, AlertCircle } from 'lucide-react';
import { useWallet } from '../context/WalletContext';
import { api } from '../utils/api';

interface CreateProposalModalProps {
  onClose: () => void;
  onSuccess: () => void;
}

const CreateProposalModal: React.FC<CreateProposalModalProps> = ({ onClose, onSuccess }) => {
  const { walletAddress } = useWallet();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  
  const [formData, setFormData] = useState({
    title: '',
    description: '',
    targetContract: '',
    functionName: '',
    callArgs: '' // JSON string
  });

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!walletAddress) {
      setError('Wallet must be connected');
      return;
    }

    setLoading(true);
    setError('');

    try {
      let parsedArgs = [];
      if (formData.callArgs) {
        try {
          parsedArgs = JSON.parse(formData.callArgs);
          if (!Array.isArray(parsedArgs)) throw new Error('Must be an array');
        } catch (e) {
          throw new Error('Call arguments must be a valid JSON array');
        }
      }

      // Generate a random proposal ID for this UI demo (normally generated by the smart contract)
      const mockProposalId = Math.floor(Math.random() * 1000000);

      await api('/governance/proposals', {
        method: 'POST',
        body: JSON.stringify({
          proposalId: mockProposalId,
          title: formData.title,
          description: formData.description,
          targetContract: formData.targetContract,
          functionName: formData.functionName,
          callArgs: parsedArgs
        })
      });

      onSuccess();
    } catch (err: any) {
      setError(err.message || 'Failed to create proposal');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-2xl max-w-lg w-full max-h-[90vh] overflow-y-auto">
        <div className="flex justify-between items-center p-6 border-b border-gray-100">
          <h2 className="text-xl font-bold text-gray-900">Create New Proposal</h2>
          <button onClick={onClose} className="text-gray-400 hover:text-gray-600 transition-colors">
            <X className="w-6 h-6" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="p-6 space-y-6">
          {error && (
            <div className="bg-red-50 text-red-600 p-4 rounded-lg flex items-start gap-3">
              <AlertCircle className="w-5 h-5 flex-shrink-0 mt-0.5" />
              <p className="text-sm">{error}</p>
            </div>
          )}

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Proposal Title</label>
            <input
              type="text"
              required
              placeholder="e.g., Update Protocol Fee to 1%"
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-600 focus:border-transparent outline-none"
              value={formData.title}
              onChange={(e) => setFormData({...formData, title: e.target.value})}
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Description</label>
            <textarea
              required
              rows={3}
              placeholder="Explain why this change is necessary..."
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-600 focus:border-transparent outline-none resize-none"
              value={formData.description}
              onChange={(e) => setFormData({...formData, description: e.target.value})}
            />
          </div>

          <div className="bg-gray-50 p-4 rounded-lg space-y-4 border border-gray-100">
            <h3 className="text-sm font-semibold text-gray-900 uppercase tracking-wider">Execution Details</h3>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Target Contract Address</label>
              <input
                type="text"
                required
                placeholder="C..."
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-600 focus:border-transparent outline-none font-mono text-sm"
                value={formData.targetContract}
                onChange={(e) => setFormData({...formData, targetContract: e.target.value})}
              />
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="col-span-2">
                <label className="block text-sm font-medium text-gray-700 mb-1">Function Name</label>
                <input
                  type="text"
                  required
                  placeholder="e.g., update_fee"
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-600 focus:border-transparent outline-none font-mono text-sm"
                  value={formData.functionName}
                  onChange={(e) => setFormData({...formData, functionName: e.target.value})}
                />
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Call Arguments (JSON Array)</label>
              <textarea
                rows={2}
                placeholder='e.g., [100] for 1% fee'
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-600 focus:border-transparent outline-none font-mono text-sm"
                value={formData.callArgs}
                onChange={(e) => setFormData({...formData, callArgs: e.target.value})}
              />
              <p className="text-xs text-gray-500 mt-1">Must be a valid JSON array.</p>
            </div>
          </div>

          <div className="flex justify-end gap-3 pt-4 border-t border-gray-100">
            <button
              type="button"
              onClick={onClose}
              className="px-6 py-2 text-gray-700 font-medium hover:bg-gray-100 rounded-lg transition-colors"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={loading}
              className="px-6 py-2 bg-indigo-600 text-white font-medium rounded-lg hover:bg-indigo-700 transition-colors disabled:bg-indigo-400 disabled:cursor-not-allowed flex items-center"
            >
              {loading ? (
                <>
                  <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin mr-2" />
                  Submitting...
                </>
              ) : (
                'Submit Proposal'
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default CreateProposalModal;
